import { VehicleCategory } from '../types';

export const VEHICLE_CATEGORIES: VehicleCategory[] = [
  {
    id: 'bike',
    name: 'Bike / Scooty',
    icon: '🛵',
    capacity: 1,
    description: 'Fastest arrival for single riders',
    baseFare: 70,
    perKmRate: 18,
    perMinRate: 2,
    waitingChargePerMin: 2,
    minimumFare: 70,
    estimatedEtaMins: 3,
  },
  {
    id: 'auto',
    name: 'Auto / Rickshaw',
    icon: '🛺',
    capacity: 3,
    description: 'Affordable open-air local travel',
    baseFare: 100,
    perKmRate: 25,
    perMinRate: 2.5,
    waitingChargePerMin: 3,
    minimumFare: 100,
    estimatedEtaMins: 4,
  },
  {
    id: 'mini',
    name: 'Mini / Small Car',
    icon: '🚗',
    capacity: 4,
    description: 'Compact economy ride for everyday travel',
    baseFare: 150,
    perKmRate: 35,
    perMinRate: 3.5,
    waitingChargePerMin: 4,
    minimumFare: 150,
    estimatedEtaMins: 5,
  },
  {
    id: 'sedan',
    name: 'Sedan / AC Car',
    icon: '🚘',
    capacity: 4,
    description: 'Standard comfortable sedan car with AC',
    baseFare: 200,
    perKmRate: 45,
    perMinRate: 4.5,
    waitingChargePerMin: 5,
    minimumFare: 200,
    estimatedEtaMins: 6,
  },
  {
    id: 'premium',
    name: 'Premium',
    icon: '✨',
    capacity: 4,
    description: 'Executive luxury rides for special comfort',
    baseFare: 250,
    perKmRate: 55,
    perMinRate: 5.5,
    waitingChargePerMin: 8,
    minimumFare: 250,
    estimatedEtaMins: 8,
  },
  {
    id: 'family',
    name: 'Family / XL',
    icon: '🚐',
    capacity: 6,
    description: 'Spacious vehicle for families & extra luggage',
    baseFare: 300,
    perKmRate: 65,
    perMinRate: 6.5,
    waitingChargePerMin: 10,
    minimumFare: 300,
    estimatedEtaMins: 10,
  },
];

export const DEFAULT_VEHICLE_CATEGORY = VEHICLE_CATEGORIES[2]; // Mini by default
