import { VehicleCategory } from '../types';

export const VEHICLE_CATEGORIES: VehicleCategory[] = [
  {
    id: 'bike',
    name: 'Bike / Scooty',
    icon: '🛵',
    capacity: 1,
    description: 'Fastest arrival for single riders',
    baseFare: 50,
    perKmRate: 25,
    perMinRate: 3,
    waitingChargePerMin: 2,
    minimumFare: 80,
    estimatedEtaMins: 3,
  },
  {
    id: 'mini',
    name: 'Mini',
    icon: '🚗',
    capacity: 4,
    description: 'Compact economy ride for everyday travel',
    baseFare: 100,
    perKmRate: 45,
    perMinRate: 5,
    waitingChargePerMin: 4,
    minimumFare: 150,
    estimatedEtaMins: 5,
  },
  {
    id: 'sedan',
    name: 'Sedan',
    icon: '🚘',
    capacity: 4,
    description: 'Standard comfortable sedan car',
    baseFare: 150,
    perKmRate: 55,
    perMinRate: 7,
    waitingChargePerMin: 5,
    minimumFare: 200,
    estimatedEtaMins: 6,
  },
  {
    id: 'premium',
    name: 'Premium',
    icon: '✨',
    capacity: 4,
    description: 'Executive luxury rides for special comfort',
    baseFare: 250,
    perKmRate: 85,
    perMinRate: 12,
    waitingChargePerMin: 10,
    minimumFare: 350,
    estimatedEtaMins: 9,
  },
  {
    id: 'family',
    name: 'Family / XL',
    icon: '🚐',
    capacity: 6,
    description: 'Spacious vehicle for families & extra luggage',
    baseFare: 300,
    perKmRate: 95,
    perMinRate: 14,
    waitingChargePerMin: 12,
    minimumFare: 450,
    estimatedEtaMins: 10,
  },
];

export const DEFAULT_VEHICLE_CATEGORY = VEHICLE_CATEGORIES[1]; // Mini by default
